import React from 'react';
import ScrollReveal from '../components/ScrollReveal';
import { Target, Shield, AlertTriangle, ChevronRight } from 'lucide-react';
import { motion } from 'framer-motion';

const SmartSignals: React.FC = () => {
  return (
    <div className="max-w-7xl mx-auto px-6 py-24 min-h-screen">
      <ScrollReveal>
        <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-blue-100 text-blue-600 rounded-lg">
                <Target size={24} />
            </div>
            <h1 className="text-4xl font-bold">Smart Signals</h1>
        </div>
        <p className="text-gray-500 mb-12 max-w-2xl">
            AI-generated entry and exit points with probabilistic confidence scores. 
            <span className="text-black font-semibold"> Past performance is not indicative of future results.</span>
        </p>
      </ScrollReveal>

      <div className="overflow-x-auto">
        <table className="w-full min-w-[800px] border-collapse">
            <thead>
                <tr className="text-left text-xs text-gray-400 uppercase tracking-wider border-b border-gray-200">
                    <th className="pb-4 pl-4">Asset</th>
                    <th className="pb-4">Signal</th>
                    <th className="pb-4">Entry Zone</th>
                    <th className="pb-4">Take Profit</th>
                    <th className="pb-4">Stop Loss</th>
                    <th className="pb-4">AI Confidence</th>
                    <th className="pb-4">Action</th>
                </tr>
            </thead>
            <tbody className="text-sm">
                {[1, 2, 3, 4, 5].map((item, i) => (
                    <motion.tr 
                        initial={{ opacity: 0, y: 10 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.1 }}
                        key={item} 
                        className="group hover:bg-gray-50 transition-colors border-b border-gray-100"
                    >
                        <td className="py-6 pl-4 font-bold">
                            <div className="flex items-center gap-3">
                                <div className="w-8 h-8 rounded-full bg-black text-white flex items-center justify-center text-xs">A{item}</div>
                                <span>ASSET_{item}</span>
                            </div>
                        </td>
                        <td className="py-6">
                            <span className={`px-3 py-1 rounded-full text-xs font-bold ${i % 2 === 0 ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                                {i % 2 === 0 ? 'LONG' : 'SHORT'}
                            </span>
                        </td>
                        <td className="py-6 font-mono text-gray-600">$142.50 - $143.00</td>
                        <td className="py-6 font-mono text-green-600 font-bold">$155.00</td>
                        <td className="py-6 font-mono text-red-500 font-bold">$138.00</td>
                        <td className="py-6">
                            <div className="flex items-center gap-2">
                                <div className="w-24 h-1.5 bg-gray-200 rounded-full overflow-hidden">
                                    <div className="h-full bg-blue-500" style={{ width: `${85 + i}%` }}></div>
                                </div>
                                <span className="font-bold text-xs">{85 + i}%</span>
                            </div>
                        </td>
                        <td className="py-6">
                            <button className="p-2 rounded-full hover:bg-gray-200 transition-colors">
                                <ChevronRight size={16} />
                            </button>
                        </td>
                    </motion.tr>
                ))}
            </tbody>
        </table>
      </div>

      <ScrollReveal delay={0.5} className="mt-12 p-6 bg-yellow-50 rounded-xl border border-yellow-100 flex gap-4 items-start">
            <AlertTriangle className="text-yellow-600 shrink-0 mt-1" />
            <div>
                <h4 className="font-bold text-yellow-800 text-sm">Risk Disclaimer</h4>
                <p className="text-yellow-700 text-xs mt-1">Trading involves substantial risk of loss. These signals are generated by AI models and should not be considered financial advice. Always do your own research.</p>
            </div>
      </ScrollReveal>
    </div>
  );
};

export default SmartSignals;